- name: Install Docker
  hosts: all
  vars:
    client_image: amwau/clientfolder:v2.0.2
    backend_image: amwau/backendfolder:v2.0.2
    app_folder: /opt/yolo
    tasks:
    - name: Update the cache
      apt:
        update_cache: yes
        upgrade: yes
         - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        update_cache: yes